<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../StreamsHttpPOST.php';

/**
 * Test class for MultipartFormData.
 * Generated by PHPUnit on 2011-08-07 at 06:49:17.
 */
class MultipartFormDataTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var MultipartFormData
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new MultipartFormData;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @todo Implement testAddFile().
	 */
	public function testAddFile() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetHeader().
	 */
	public function testGetHeader() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetContentString().
	 */
	public function testGetContentString() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
