<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../StreamsHttpPOST.php';

/**
 * Test class for StreamsHttpPOST.
 * Generated by PHPUnit on 2011-08-06 at 17:44:49.
 */
class StreamsHttpPOSTTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var StreamsHttpPOST
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new StreamsHttpPOST('http://example.com');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @todo Implement testPost().
	 */
	public function testPost() {
		$contents = $this->object->post();
		$expected = "RFC 2606";
		$this->assertContains($expected, $contents);
	}

	/**
	 * @todo Implement testPost().
	 */
	public function testPostToLocalhost() {
		$this->object = new StreamsHttpPOST('http://localhost/outputPost.php');
		$data = array('foo' => 'bar');
		$this->object->addData($data);
		$contents = $this->object->post();
		$expected = "bar";
		$this->assertContains($expected, $contents);
	}

		/**
	 * @todo Implement testPost().
	 */
	public function testPostFilesToLocalhost() {
		$data = array('foo' => 'bar');
		$multipartFormData = new MultipartFormData($data);
		$multipartFormData->addFile('test', __FILE__);
//		var_dump($multipartFormData->getHeader(), $multipartFormData->getContentString());
		echo $multipartFormData->getContentString();
		$this->object = new StreamsHttpPOST('http://localhost/outputPost.php',$multipartFormData);
		$contents = $this->object->post();
		$expected = "bar";
		var_dump($contents);
		$this->assertContains($expected, $contents);
	}
		/**
	 * @todo Implement testPost().
	 */
	public function testGetResponseCode() {
		$this->object->post();
		$code = $this->object->getResponseCode();
		$expected = 302;
		$this->assertSame($expected, $code);
	}



}

?>
