<?php


require_once dirname(__FILE__) . '/../StreamsHttpPOST.php';

/**
 * Test class for StreamsHttpPOST.
 * Generated by PHPUnit on 2011-08-06 at 17:44:49.
 */
class StreamsHttpPOSTTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var StreamsHttpPOST
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new StreamsHttpPOST('http://example.com');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	public function testPost() {
		$contents = $this->object->post();
		$expected = "RFC 2606";
		$this->assertContains($expected, $contents);
	}

	public function testPostToLocalhost() {
		$this->object = new StreamsHttpPOST('http://localhost/outputPost.php');
		$data = array('foo' => 'bar');
		$this->object->addData($data);
		$contents = $this->object->post();
		$expected = "bar";
		$this->assertContains($expected, $contents);
	}

	public function testPostToLocalhostMultipleFields() {
		$this->object = new StreamsHttpPOST('http://localhost/outputPost.php');
		$data = array('foo' => 'bar', 'baz' => 'bat');
		$this->object->addData($data);
		$contents = $this->object->post();
		$expected = "bat";
		$this->assertContains($expected, $contents);
		var_dump($contents);
	}

	public function testPostFilesToLocalhost() {
		$data = array('foo' => 'bar');
		$multipartFormData = new MultipartFormData($data);
		$filename = __DIR__.'/testLoad.txt';
		$multipartFormData->addFile('test',$filename);
		$this->object = new StreamsHttpPOST('http://localhost/outputPost.php',$multipartFormData);
		$contents = $this->object->post();
		$expected = "bar";
		$this->assertContains($expected, $contents);
		$this->assertContains(basename($filename), $contents);
		$this->assertContains(file_get_contents($filename), $contents);
		var_dump($contents);
	}


	public function testAddFilesToLocalhost() {
		$this->object = new StreamsHttpPOST('http://localhost/outputPost.php');
		$filename = __DIR__.'/testLoad.txt';
		$this->object->addFile('test', $filename);
		$contents = $this->object->post();
		$this->assertContains(basename($filename), $contents);
		$this->assertContains(file_get_contents($filename), $contents);
	}
	public function testGetResponseCode() {
		$this->object->post();
		$code = $this->object->getResponseCode();
		$expected = 302;
		$this->assertSame($expected, $code);
	}
}
